INSERT INTO Joueurs (Nom, Equipe, Poste, Numéro)
VALUES ('Keylor Navas',2,'Gardien',1),
    ('Sergio Rico',2,'Gardien',16),
    ('Alexandre Letellier', 2,'Gardien',30),
    ('Presnel Kimpembe',2,'Défenseur',3),
    ('Thilo Keher',2,'Défenseur',4),
    ('Marquinhos',2,'Défenseur',5), 
    ('Juan Bernat',2,'Défenseur',14),
    ('Layvin Kurzawa',2,'Défenseur',20),
    ('Abdou Diallo',2,'Défenseur',22),
    ('Alessandro Florenzi',2,'Défenseur',24),
    ('Mitchel Bakker',2,'Défenseur',25),
    ('Colin Dagba',2,'Défenseur',31),
    ('Marco Veratti',2,'Milieu',6),
    ('Leandro Paredes',2,'Milieu',8),
    ('Angel Di Maria',2,'Milieu',11),
    ('Rafinha', 2, 'Milieu', 12),
    ('Danilo Pereira',2,'Milieu',15),
    ('Pablo Sarabia',2,'Milieu',19),
    ('Ander Herrera',2,'Milieu',21),
    ('Julian Draxler',2,'Milieu',23),
    ('Idrissa Gueye',2,'Milieu',27),
    ('Kylian Mbappé',2,'Attaquant',7),
    ('Mauro Icardi',2,'Attaquant',9),
    ('Neymar', 2, 'Attaquant', 10),
    ('Moise Kean',2,'Attaquant',18)